---
- hosts: run
  vars:
   wallet_image: "ka2er/crypto-wallet-{{ wallet }}"
   wallet_path: "{{ data_path }}/{{ wallet }}"
  become: yes
  become_method: sudo
  gather_facts: false
  #become_ask_pass: true
  #remote_user: root
  tasks:
  - name: "create local guest wallet data directory : {{ wallet_path }}"
    file:
      path: "{{ wallet_path }}/.{{ wallet }}"
      state: directory
      mode: 0755
      recurse: yes
  - name: "deploy tools - debug"
    template:
      src: run/debug.sh.j2
      dest: "{{ wallet_path }}/debug.sh"
      mode: 0755
  - name: "deploy tools - logs"
    template:
      src: run/logs.sh.j2
      dest: "{{ wallet_path }}/logs.sh"
      mode: 0755
  - name: check python-docker is present
    package:
      name: 
        - "python-docker"
      state: latest
  - name: "get wallet docker image ({{ wallet_image }})"
    docker_image:
      name: "{{ wallet_image }}"
      state: present
      force: yes
  - name: start wallet
    docker_container:
      name: "{{ wallet }}_wallet"
      image: "{{ wallet_image }}"
      state: started
      volumes: 
        "{{ wallet_path }}:/home/wallet"
#  - name: check user permissions
  - name: "Config set staking mode + rpc config"
    template:
      src: run/template.conf.j2
      dest: "{{ wallet_path }}/.{{ wallet}}/{{ wallet }}.conf"
      backup: yes
  - name: get wallet public address
#    command: "docker exec -u wallet {{ wallet }}_wallet bash -l -c /usr/local/bin/{{ wallet }}-cli getaddress ''"
    command: "docker exec -u wallet {{ wallet }}_wallet /usr/local/bin/{{ wallet }}-cli getaddress ''"

#  - name: encrypt wallet
#  - name: unlock wallet
#  - name: backup wallet
    #  - name: write the quagga config file
    #template: src=quagga.j2 dest=/etc/quagga/Quagga.conf
    #notify:
    #- restart quagga
    # - name: ensure quagga is running
    #service: name=quagga state=started
    #handlers:
    #- name: restart quagga
    #  service: name=quagga state=restarted
